#!/usr/local/bin/perl -w

# Copyright (C) 2009, Byron Grobe
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Byron Grobe nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY Byron Grobe ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL Byron Grobe BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


use IO::Socket;
#use IO::Socket::INET6;
use Sys::Hostname;
use DBI;

use strict;
use warnings;

my $socket;

#Configuration
my $server = "irc.freenode.net";
#my $local = "2001:470:1f07:96f:feed:1:0:face";
my $port = 6667;
my $nick = "cercinus";
my $host = hostname( );
my $realname = "Byron Grobe";
my $pass = $ARGV[0];
my %evallist = ();
my $evalnum = 0;

my $reload=0; #DO NOT MODIFY

my $conn = DBI->connect("dbi:SQLite:dbname=users.db", "", "", { RaiseError => 1, AutoCommit => 0 });

my @autojoin = ("#barsoom");

#Pseudo-module configuration
my $do_autojoin		= "true";

my @autovoice_chans	= ("#bots");

my $do_pub_ban		= "true";
my $do_pub_voice	= "true";
my $do_pub_op		= "true";

my $whois_ident;
my $whois_hostmask;
my $whois_realname;

#$SIG{CHLD} = sub { my $pid = wait; do_print "PRIVMSG #bots :RX SIGCHLD from $pid\n"; delete $evallist{$pid}; };
$SIG{CHLD} = 'IGNORE';

open(my $log, "> ia.log") or die ("Could not open log file: $!\n");

sub do_print
{
	my @line = @_;

	print $socket "@line";
	print $log    "@line";
}


sub do_connect()
{
open(my $ident, "> .oidentd.conf") or die "Could not open: $!\n";
print $ident "global { reply \"DakBroadbent\" }";
close $ident;
$socket = IO::Socket::INET->new(PeerAddr => $server,
				PeerPort => $port,
				Proto	 => "tcp",
				Domain => AF_INET6,
				#LocalAddr => $local,
				Type	 => SOCK_STREAM)
				or die "Couldn't Connect to $server:$port : $@\n";

$socket->autoflush(1);

do_print "PASS $pass\n";
do_print "NICK $nick\n";
do_print "USER $nick $host $server :$realname\n";
do_print "PRIVMSG cluros :ident $pass\n";
my $i=0;
for($i=0;$i<10;$i++)
{
	if(defined(my $in=<$socket>))
	{
		chomp $in;
		if($in =~ /PING/)
		{
			(undef, my $ret) = split(/\ /,$in);
			do_print "PONG $ret\r\n";
		}
	}
	else
	{
		sleep 1;
	}
}

if($do_autojoin eq "true")
{
	foreach my $chan (@autojoin)
	{
		do_print ":$nick JOIN $chan\n";
	}
}
}

sub getinfo
{
	my @chunks = @_;

	my $is_pm = pop(@chunks);

	(my $person, undef, my $hostmask) = split(/([!])/, $chunks[0]);
	$person =~ s/([:])//;

	my $channel = $chunks[2];
	chomp($channel);
	$channel =~ s/([:])//;
	if($is_pm ne "true")
	{
		chop($channel);
	}

	(my $ident, undef, $hostmask) = split(/([@])/, $hostmask);

	return ($person, $ident, $hostmask, $channel);
}


sub autovoice
{
	my @chunks = @_;
	(my $person, my $ident, my $hostmask, my $channel) = getinfo(@chunks, "false");

	my $tmp;
	my $i=0;
	while(defined ($tmp = $autovoice_chans[$i]))
	{
		if($channel eq $tmp)
		{
			do_print ":$nick MODE $channel +v $person\n";
		}
		$i++;
	}
# Code for SDF IRC
#	$ident =~ s/\~//;
#	if($hostmask =~ /sdf/)
#	{
#		print STDERR "Checking $ident uinfo\n";
#		open(my $cin, "ssh iceland 'uinfo $person'|");
#		while(defined(my $in=<$cin>))
#		{
#			chomp $in;
#			if($in =~ /MetaARPA/)
#			{
#				do_print ":$nick MODE $channel +o $person\n";
#			}
#		}
#		close $cin;
#	}
}

sub check_auth
{
	my @chunks = @_;
	(my $ident, my $hostmask) = @chunks;

	#my $conn = DBI->connect("dbi:SQLite:dbname=/home/grobe0ba/src/fnpb/users.db", "", "", { RaiseError => 1, AutoCommit => 0 });

	my $stmt = $conn->prepare("SELECT * FROM USERS WHERE IDENT=\"$ident\" AND HOSTMASK=\"$hostmask\";");

	$stmt->execute();

	my @row = $stmt->fetchrow_array();

	$conn->commit();
	$stmt->finish();
	#$conn->disconnect();

	if(@row)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

sub add_auth
{
	my @chunks = @_;
	(my $ident, my $hostmask, my $channel, my $who) = @chunks;

	#my $conn = DBI->connect("dbi:SQLite:dbname=./users.db", "","");

	my $row = $conn->do("INSERT INTO USERS (IDENT, HOSTMASK) VALUES (\"$ident\", \"$hostmask\");");

	$conn->commit();
	#$conn->disconnect();

	if($row)
	{
		chomp $hostmask;
		do_print ":$nick PRIVMSG $channel :$who, $ident\@$hostmask added to authorized users database.\n";
	}
	else
	{
		chomp $hostmask;
		do_print ":$nick PRIVMSG $channel :$who, $ident\@$hostmask not added to authorized users database.\n";
	}
}

sub del_auth
{
	my @chunks = @_;
	(my $ident, my $hostmask, my $channel, my $who) = @chunks;

	#my $conn = DBI->connect("dbi:SQLite:dbname=./users.db", "","");

	my $row = $conn->do("DELETE FROM USERS WHERE IDENT=\"$ident\" AND HOSTMASK=\"$hostmask\";");

	$conn->commit();
	#$conn->disconnect();

	if($row)
	{
		do_print ":$nick PRIVMSG $channel :$who, $ident\@$hostmask removed from authorized users database.\n";
	}
	else
	{
		do_print ":$nick PRIVMSG $channel :$who, $ident\@$hostmask not removed from authorized users database.\n";
	}
}

sub list_auth
{
	my @chunks = @_;

	my $channel = shift @chunks;

	#my $conn = DBI->connect("dbi:SQLite:dbname=./users.db", "","");

	my $stmt = $conn->prepare("SELECT IDENT,HOSTMASK FROM USERS;");

	$stmt->execute();

	#$conn->commit();

	while( (my $ident, my $hostmask) = $stmt->fetchrow_array())
	{
		do_print ":$nick PRIVMSG $channel :$ident\@$hostmask\n";
	}

	$stmt->finish();
	#$conn->disconnect();
}

sub invitejoin
{
	my @chunks = @_;
	(my $person, my $ident, my $hostmask, my $channel) = getinfo(@chunks, "true");

	print STDERR "$channel :$person!$ident\@$hostmask : checking for authorization\n";

	my $cmd = $chunks[3];
	$cmd =~ s/://;

	do_print ":$nick JOIN $cmd\n";
}


sub privmsg
{
	my @chunks = @_;
	(my $person, my $ident, my $hostmask, my $channel) = getinfo(@chunks, "true");

	print STDERR "$channel :$person!$ident\@$hostmask : checking for authorization\n";

	my $cmd = $chunks[3];
	$cmd =~ s/://;

	($cmd, my @args) = split(/\ /, $cmd);

	if(($cmd =~ /\!request/i ))
	{
		do_print ":$nick KICK $channel $person :Read the topic, dumbass...\n";
	}

	if(($cmd =~ /\.say/i ))
	{
		do_print ":$nick PRIVMSG $channel :@args\n";
	}
	if(($cmd =~ /\.action/i) )
	{
		do_print ":$nick PRIVMSG $channel :\001ACTION @args \001\n";
	}

	if(($cmd eq ".google"))
	{
		my $tmp;
		my $newargs = shift @args;

		foreach $tmp (@args)
		{
			$newargs = "$newargs+$tmp";
		}

		do_print ":$nick PRIVMSG $channel :http://www.google.com/search?q=$newargs\n";
	}

	if(($cmd =~ /\.port/i) )
	{
	    if (@args < 2)
	    {
		do_print ":$nick PRIVMSG $person :Usage: .port (name|key) port [| nick]\n";
		return;
	    }
	    my $search_type = shift @args;
	    my $pkg_name = shift @args;
	    my $path = "";
	    my $info = "";
	    my $found = 0;

	    if($args[0] eq "|")
	    {
		$person = $args[1];
	    }

	    open(my $make_in, "/usr/bin/make -C /usr/ports search $search_type=$pkg_name|") or die "Could not fork: $!\n";
	    while(defined (my $line=<$make_in>))
	    {
		chomp $line;
		if($line =~ /^Path:/)
		{
		    $line =~ s/Path: //;
		    $info = $line;
		    $found = 1;
		}
		if($line =~ /^Info:/)
		{
		    do_print ":$nick PRIVMSG $person :$info $line\n";
		    sleep 1;
		    $info = "";
		}
	    }

	    if($found==0)
	    {
		do_print ":$nick PRIVMSG $channel :No port found\n";
	    }
	}

	if(($cmd eq ".images"))
	{
		my $tmp;
		my $newargs = shift @args;

		foreach $tmp (@args)
		{
			$newargs = "$newargs+$tmp";
		}

		do_print ":$nick PRIVMSG $channel :http://images.google.com/images?q=$newargs\n";
	}
{
	my $tmp = $cmd;
	chop $tmp;
	$tmp =~ s/\001//g;

	if(($tmp =~ /VERSION/i ))
	{
		my $sysinfo = "";
		if(open(my $in, "/usr/bin/sysinfo |"))
		{
			while(defined (my $line = <$in>))
			{
				chomp $line;
				$sysinfo = $line;
			}
		}
		else
		{
			$sysinfo = "Could not access system information.";
		}
		#Enable this reply at your own risk. Some networks (like freenode) detect this as being a virus-bot-thingy when its enabled. The bot follows the RFC
		#specifications. freenode doesn't.
		do_print ":$nick NOTICE $person :\001VERSION perlbot-current $sysinfo Copyright (C) Byron Grobe. All Rights Reserved.\001\n";
		#print STDERR ":$nick NOTICE $person \001VERSION perlbot-current:0.1:perl\001\n";
	}
	if(($tmp =~ /FINGER/i ))
	{
		do_print ":$nick NOTICE $person \001FINGER :Reply to FINGER\001\n";
	}
	if(($tmp =~ /PING/i ))
	{
		my $tmp = time( );
		do_print ":$nick NOTICE $person \001PING @args\001\n";
	}
}
	
	#if(($ident eq $controller_ident) && ($hostmask eq $controller_hostmask))
	if(check_auth($ident, $hostmask))
	{
		print STDERR "$channel :$person!$ident\@$hostmask : authorized\n";
		my $cmd = $chunks[3];
		$cmd =~ s/://;

		($cmd, my @args) = split(/\ /, $cmd);

		print STDERR "$channel :$person!$ident\@$hostmask : command $cmd\n";

		if(($cmd =~ /\.msg/i))
		{
			my $recp = shift @args;
			do_print "PRIVMSG $recp :@args\n";
		}

		if(($cmd =~ /\.whois/i ))
		{
			do_print ":$nick WHOIS @args\n";
		}
		if(($cmd =~ /\.setwhois/i ))
		{
			($whois_ident, $whois_hostmask) = @args;
			chop $whois_hostmask;
		}
		if(($cmd =~ /\.adduser/i ))
		{
			add_auth($whois_ident, $whois_hostmask, $channel, $person);
		}
		if(($cmd =~ /\.deluser/i ))
		{
			del_auth($whois_ident, $whois_hostmask, $channel, $person);
		}
		if(($cmd =~ /\.isauth/i ))
		{
			if(check_auth($whois_ident, $whois_hostmask))
			{
				do_print ":$nick PRIVMSG $channel :$person, $whois_ident\@$whois_hostmask is an authorized user.\n";
			}
			else
			{
				do_print ":$nick PRIVMSG $channel :$person, $whois_ident\@$whois_hostmask is not an authorized user.\n";
			}
		}
		if(($cmd =~ /\.listauth/i ))
		{
			list_auth($channel);
		}

		if(($cmd =~ /\.die/i ))
		{
			do_print ":$nick QUIT :@args\n";
		}
		if(($cmd =~ /\.reload/i ))
		{
			$reload=1;
			do_print ":$nick QUIT :Reloading\n";
		}

		if(($cmd =~ /\.cycle/i ))
		{
			do_print ":$nick PART $channel :Cycle requested by $person\n";
			do_print ":$nick JOIN $channel\n";
		}
		if(($cmd =~ /\.join/i ))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick JOIN $tmp\n";
			}
		}

		if(($cmd =~ /\.part/i ))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick PART $tmp\n";
			}
		}

		if(($cmd =~ /\.ban/i ) && ($do_pub_ban eq "true"))
		{
			#my $tmp;
			#while(defined ($tmp = shift @args))
			#{
				#do_print ":$nick WHOIS $tmp\n";
				#do_print ":$nick MODE $channel +b $tmp\n";
				do_print ":$nick MODE $channel +b *!*\@$whois_hostmask\n";
			#}
		}
		if(($cmd =~ /\.unban/i ) && ($do_pub_ban eq "true"))
		{
			#my $tmp;
			#while(defined ($tmp = shift @args))
			#{
				#do_print ":$nick MODE $channel -b $tmp\n";
				do_print ":$nick MODE $channel -b *!*\@$whois_hostmask\n";
			#}
		}
		if(($cmd =~ /\.voice/i ) && ($do_pub_voice eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel +v $tmp\n";
			}
		}
		if(($cmd =~ /\.devoice/i ) && ($do_pub_voice eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel -v $tmp\n";
			}
		}
		if(($cmd =~ /\.op/i ) && ($do_pub_op eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel +o $tmp\n";
			}
		}
		if(($cmd =~ /\.deop/i ) && ($do_pub_op eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel -o $tmp\n";
			}
		}
		if(($cmd =~ /\.hop/i ) && ($do_pub_op eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel +h $tmp\n";
			}
		}
		if(($cmd =~ /\.dehop/i ) && ($do_pub_op eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel -h $tmp\n";
			}
		}
		if(($cmd =~ /\.admin/i ) && ($do_pub_op eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel +a $tmp\n";
			}
		}
		if(($cmd =~ /\.deadmin/i ) && ($do_pub_op eq "true"))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				do_print ":$nick MODE $channel -a $tmp\n";
			}
		}
		if(($cmd =~ /\.mkick/i ))
		{
			my $tmp;
			while(defined ($tmp = shift @args))
			{
				chomp $tmp;
				do_print ":$nick KICK $channel $tmp :Requested ($person)\n";
			}
		}
		if(($cmd =~ /\.kick/i))
		{
			my $tmp = shift @args;
			chomp @args;
			do_print ":$nick KICK $channel $tmp :@args ($person)\n";
		}
		if(($cmd =~ /\.mode/i ))
		{
			do_print ":$nick MODE $channel @args\n";
		}
		if(($cmd =~ /\.eval/i ))
		{
			die "Could not fork: $!\n" unless defined (my $evalpid = fork());
			$evalnum = $evalnum + 1;
			my $key = "eval$evalnum";
			$evallist{$key} = $evalpid;
			if (!$evalpid)
			{
				eval "@args";
				exit 0;
			}
		}
		if(($cmd =~ /\.listeval/i ))
		{
			do_print "PRIVMSG $channel :ID\tPID\n";
			while( my ($key, $value) = each(%evallist))
			{
				do_print "PRIVMSG $channel :$key\t$value\n";
			}
		}
		if(($cmd =~ /\.stopeval/i ))
		{
			while (my ($key, $value) = each(%evallist))
			{
				my $chk = join("",@args);
				if( grep(/\Q$key/i,$chk))
				{
					do_print "PRIVMSG $channel :Attempting to kill PID $value, Eval ID @args\n";
					kill 9,$value;
				}
			}
		}
	}
	else
	{
		print STDERR "$channel :$person!$ident\@$hostmask : access denied\n";
	}
}

sub whois
{
	my @chunks = @_;

	my @info = split(/\ /, $chunks[3]);

	(undef, $whois_ident, $whois_hostmask) = @info;

}

sub do_io
{
	#die "could not fork: $!\n" unless defined (my $pid1 = fork( ));
	my $io_x = select($socket);

	#if($pid1)
	if($io_x)
	{
		while(defined (my $line = <$socket>))
		{
			while (my($eval, $pid)=each(%evallist))
			{
				if(!(kill 0,$pid))
				{
					delete $evallist{$eval};
				}
			}
			chop($line);
			print STDOUT "$line\n";

			my @chunks = split(/\ /, $line, 4);

			my $var = $chunks[1];
			chomp($var);

			if($var eq "JOIN") { autovoice(@chunks); }
			if($var eq "PRIVMSG") { privmsg(@chunks); }
			if($var eq "INVITE") { invitejoin(@chunks); }
			if($var eq "311") { whois(@chunks); }
		}
		#$conn->disconnect();
		#kill("TERM" => $pid1);
	}
	else
	{
		while(defined (my $line = <STDIN>))
		{
			print $socket $line;
			print $log $line;
		}
	}
	if($reload)
	{
		#open(my $nsfh, "< perlbot") or die "Could not open self: $!\n";
		#my @nssize = stat $nsfh;
		#sysread $nsfh,my $ns,$nssize[7];
		#close $nsfh;
		#eval $ns;
		reload();
	}
}

sub reload
{
	open(my $nsfh, "< perlbot") or die "Could not open self: $!\n";
	my @nssize = stat $nsfh;
	sysread $nsfh,my $ns,$nssize[7];
	close $nsfh;
	eval $ns;
}

sub do_keepalive()
{
	while(1)
	{
		sleep 60;
		print $socket ":$nick PING $server\n";
	}
}

do_connect();
die "could not fork: $!\n" unless defined(my $pid=fork( ));

if($pid)
{
	do_io();
	reload();
	kill("TERM" => $pid);
}
else
{
	do_keepalive();
}
